package com.example.fit_iq.ui.Presentation

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF794F81)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFDD6FF)
val onPrimaryContainerLight = Color(0xFF603768)
val secondaryLight = Color(0xFF156B54)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFA4F2D5)
val onSecondaryContainerLight = Color(0xFF00513E)
val tertiaryLight = Color(0xFF82524C)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDAD5)
val onTertiaryContainerLight = Color(0xFF673B36)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF7FA)
val onBackgroundLight = Color(0xFF1F1A1F)
val surfaceLight = Color(0xFFFFF7FA)
val onSurfaceLight = Color(0xFF1F1A1F)
val surfaceVariantLight = Color(0xFFECDFE9)
val onSurfaceVariantLight = Color(0xFF4D444C)
val outlineLight = Color(0xFF7E747D)
val outlineVariantLight = Color(0xFFCFC3CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342F34)
val inverseOnSurfaceLight = Color(0xFFF9EEF5)
val inversePrimaryLight = Color(0xFFE9B5EF)
val surfaceDimLight = Color(0xFFE1D7DE)
val surfaceBrightLight = Color(0xFFFFF7FA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFCF1F8)
val surfaceContainerLight = Color(0xFFF6EBF2)
val surfaceContainerHighLight = Color(0xFFF0E5EC)
val surfaceContainerHighestLight = Color(0xFFEAE0E7)



val primaryDark = Color(0xFFE9B5EF)
val onPrimaryDark = Color(0xFF472150)
val primaryContainerDark = Color(0xFF603768)
val onPrimaryContainerDark = Color(0xFFFDD6FF)
val secondaryDark = Color(0xFF88D6BA)
val onSecondaryDark = Color(0xFF00382A)
val secondaryContainerDark = Color(0xFF00513E)
val onSecondaryContainerDark = Color(0xFFA4F2D5)
val tertiaryDark = Color(0xFFF5B7B0)
val onTertiaryDark = Color(0xFF4C2521)
val tertiaryContainerDark = Color(0xFF673B36)
val onTertiaryContainerDark = Color(0xFFFFDAD5)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF171217)
val onBackgroundDark = Color(0xFFEAE0E7)
val surfaceDark = Color(0xFF171217)
val onSurfaceDark = Color(0xFFEAE0E7)
val surfaceVariantDark = Color(0xFF4D444C)
val onSurfaceVariantDark = Color(0xFFCFC3CD)
val outlineDark = Color(0xFF988D97)
val outlineVariantDark = Color(0xFF4D444C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE0E7)
val inverseOnSurfaceDark = Color(0xFF342F34)
val inversePrimaryDark = Color(0xFF794F81)
val surfaceDimDark = Color(0xFF171217)
val surfaceBrightDark = Color(0xFF3D373D)
val surfaceContainerLowestDark = Color(0xFF110D11)
val surfaceContainerLowDark = Color(0xFF1F1A1F)
val surfaceContainerDark = Color(0xFF231E23)
val surfaceContainerHighDark = Color(0xFF2E282E)
val surfaceContainerHighestDark = Color(0xFF393338)

val CustomBlue = Color(0xFF1E88E5)
val CustomGreen = Color(0xFF43A047)